[package]
name = "ecfft_utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pasta_curves = "0.4"
group = "0.12"
ff = "0.12"
rayon = "1.5.1"
